<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>1.0.3</Version>
		<Authors>Uzair Shafi</Authors>
		<PackageId>SecureOps</PackageId>
		<Description>Feature-based authorization for ASP.NET Core with support for permission claims, caching, and minimal API endpoints.</Description>
		<PackageTags>authorization permissions aspnetcore jwt security</PackageTags>
		<RepositoryUrl>https://github.com/eruzairshafi/SecureOps</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\SecureOps.xml</DocumentationFile>
		<PackageReadmeFile>NuGetReadme.md</PackageReadmeFile>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="RazorLight" Version="2.3.1" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.41" />
	</ItemGroup>	
	
	<ItemGroup>
		<None Include="NuGetReadme.md" Pack="true" PackagePath="" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Presentation\UI\Views\**\*.cshtml" />
	</ItemGroup>
</Project>
